name: CI Build for Custom Docker Action
on:
  push:
    branches: [ main ]
    paths: [ custom-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: weather-action
        uses: ./custom-docker-action
        with:
          city: 'Johannesburg'

      - name: Output weather fetched in the container
        run: echo "${{ steps.weather-action.outputs.weather }}"
